### ISSUE TITLE
Add support for renaming references in moved files

### ISSUE THREAD

**Issue by ahutchings** [jurassix/atom-refactoring-codemods#10]
jurassix/refactoring-codemods#1

**Comment by jurassix** [comment]
refactoring-codemods has a new transform in v0.0.7 import-relative-transform that updates all relative import/require paths to be relative to the new file location. 

I have bumped the lib, but now need to determine if the file has been moved out of the current directory and if so send the moved file through this transform. We may also want to only use a subset of user options passed to jscodeshift since this file could have been excluded...

**Comment by ahutchings** [comment]
WFM
